name: Fetch Azure Arc Agent Info and Update README

on:
  schedule:
    - cron: '0 0 * * SUN'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install and Import MSCatalog PowerShell Module
      run: | 
        Install-Module MSCatalog -Repository PSGallery -Force -Scope CurrentUser
        Import-Module MSCatalog
      shell: pwsh

    - name: Execute PowerShell Script and Save Output
      run: |
        $result = .\Get-AzureConnectedMachineAgentVersion.ps1 | Out-String
        $result | Out-File -FilePath .\output.json -Encoding utf8
      shell: pwsh

    - name: Update README.md
      run: |
        $data = Get-Content .\output.json | ConvertFrom-Json
        $markdownTable = "Title | Version | KB Article`n---- | ------- | ----------`n"
        foreach ($item in $data) {
            $markdownTable += "$($item.Title) | $($item.Version) | $($item.KBArticle)`n"
        }
        $readmeContent = Get-Content .\README.md
        $updatedReadme = $readmeContent + "`n## Azure Agent Information`n" + $markdownTable
        $updatedReadme | Set-Content .\README.md
      shell: pwsh
        
    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: Save Arc Files
        skip_checkout: true
